version: "3.8"

services:
    app:
        image: traefik:v2.11.8
        ports:
            - 80:80
            - 443:443
        command:
            - --api
            - --api.insecure=true
            - --api.dashboard=true
            - --api.debug=true
            - --log
            - --log.level=DEBUG
            - --providers.docker=true
            - --providers.docker.swarmMode=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=network-swarm
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls.certresolver=letsencrypt
            - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
            - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
            - --certificatesresolvers.letsencrypt.acme.email=claudio@techprox.com.br
            - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
            - --accesslog

        volumes:
            - /swarm/infra/traefik/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - network-swarm
        secrets:
            - traefik_acesso
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-3-1
            labels:
                # Configurações do serviço
                # ----------------------------
                # Habilitando o domínio
                - traefik.enable=true
                - traefik.http.routers.traefik.rule=Host(`tf.techprox.com.br`)
                - traefik.http.routers.traefik.service=api@internal
                # Configurações de solicitação de senha
                - traefik.http.routers.traefik.middlewares=test-auth
                - traefik.http.middlewares.test-auth.basicauth.users=techprox:$2y$05$Mv51AHAlGrOSF3vBCE.vzuEP24of9H/BzmjdI2j.m10zY/BC5zPte
                # Habilitando porta
                - traefik.http.services.traefik.loadbalancer.server.port=8080
                # Habilitando Checagem
                - traefik.http.services.traefik.loadbalancer.healthcheck.path=/health
                - traefik.http.services.traefik.loadbalancer.healthcheck.interval=7s
                - traefik.http.services.traefik.loadbalancer.healthcheck.timeout=5s
networks:
    network-swarm:
        external: true
secrets:
  traefik_acesso:
    external: true