version: "3.8"

services:
  nextcloud-db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /swarm/front/nextcloud/db:/var/lib/mysql
      - /tmp:/tmp
    networks:
      - network-swarm
    environment:
      - MYSQL_ROOT_PASSWORD=gamba891330
      - MYSQL_PASSWORD=gamba891330
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-3-1
  nextcloud-app:
    image: nextcloud:stable
    volumes:
      - /swarm/front/nextcloud/html:/var/www/html
    networks:
      - network-swarm
    environment:
      - MYSQL_PASSWORD=gamba891330
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - REDIS_PORT=6379

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-3-1
      labels:
        # Configurações do serviço
        #-------------------------
        - traefik.enable=true
        - traefik.http.routers.nextcloud.rule=Host(`cloud.techprox.com.br`)
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        #- traefik.http.services.nextcloud.loadbalancer.healthcheck.path=/health
        #- traefik.http.services.nextcloud.loadbalancer.healthcheck.interval=7s
        #- traefik.http.services.nextcloud.loadbalancer.healthcheck.timeout=5s
  nextcloud-redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-3-1
    volumes:
      - /swarm/front/nextcloud/redis:/data
    networks:
      - network-swarm

networks:
  network-swarm:
    external: true
