version: "3.7"
services:
  wordpress-app:
    image: wordpress:php8.3
    environment:
      WORDPRESS_DB_HOST: wordpres-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: gamba891330
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /swarm/front/wordpress/www:/var/www/html
    networks:
      - network-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-3-1
      labels:
        # Configurações do serviço
        #-------------------------
        - traefik.enable=true
        - traefik.http.routers.wordpress.rule=Host(`www.techprox.com.br`)
        - traefik.http.services.wordpress.loadbalancer.server.port=80
        #- traefik.http.services.wordpress.loadbalancer.healthcheck.path=/health
        #- traefik.http.services.wordpress.loadbalancer.healthcheck.interval=7s
        #- traefik.http.services.wordpress.loadbalancer.healthcheck.timeout=5s
  wordpres-db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: gamba891330
      MYSQL_ROOT_PASSWORD: gamba891330
    volumes:
      - /swarm/front/wordpress/db:/var/lib/mysql
    networks:
      - network-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == docker-3-1
networks:
  network-swarm:
    external: true
volumes:
  wordpress:
