version: "3.2"

services:
    agent:
        image: portainer/agent:2.20.3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - network-swarm
        deploy:
            mode: global
            placement:
                constraints: [node.platform.os == linux]
    app:
        image: portainer/portainer-ce:2.20.3
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        volumes:
            - /swarm/infra/portainer:/data
        networks:
            - network-swarm
            # ports:
            #     - "9000:9000"
            #     - "8000:8000"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-3-1
            labels:
                # Configurações do serviço
                #-------------------------
                - traefik.enable=true
                - traefik.http.routers.portainer.rule=Host(`pt.techprox.com.br`)
                - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
    network-swarm:
        external: true
