version: '3.7'

services:
    minio:
        image: minio/minio:RELEASE.2024-07-31T05-46-26Z-cpuv1
        volumes:
            - /swarm/front/minio/data:/data
        networks:
            - network-swarm
        environment:
            MINIO_ROOT_USER: techprox
            MINIO_ROOT_PASSWORD: 9dZKLAegkkMpUjvTkA3z
            MINIO_BROWSER_REDIRECT_URL:
        command:  minio server /data --console-address ":9091" --address ":9090"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.hostname == docker-1-1
            labels:
                # Configurações do serviço
                #-------------------------
                - traefik.enable=true
                - traefik.http.routers.minio.rule=Host(`minio.techprox.com.br`)
                - traefik.http.routers.minio.service=minio-service
                - traefik.http.services.minio-service.loadbalancer.server.port=9090
                - traefik.http.routers.minio-admin.rule=Host(`minio-admin.techprox.com.br`)
                - traefik.http.routers.minio-admin.service=minio-admin-service
                - traefik.http.services.minio-admin-service.loadbalancer.server.port=9091
networks:
  network-swarm:
    external: true
