version: "3.5"

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=G@mba891330
            - PGDATA=/data/postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - /swarm/back/postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - network-swarm
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-2-2
        healthcheck: # Healthcheck docs: <https://docs.docker.com/engine/reference/builder/#healthcheck>
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 2s
            timeout: 5s
            start_period: 2s

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: "claudio@techprox.com.br"
            PGADMIN_DEFAULT_PASSWORD: "G@mba891330"
            PGADMIN_LISTEN_PORT: 80
        volumes:
            - pgadmin:/var/lib/pgadmin
            - /swarm/front/pgadmin/backup:/backup
        networks:
            - network-swarm
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-2-2
            labels:
                # Configurações do serviço
                #-------------------------
                - traefik.enable=true
                - traefik.http.routers.pgadmin.rule=Host(`db.techprox.com.br`)
                - traefik.http.services.pgadmin.loadbalancer.server.port=80
networks:
    network-swarm:
        external: true
volumes:
    pgadmin:
    postgres:
