version: "3.8"

services:
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - '/swarm/back/redis:/data'
        networks:
            - network-swarm
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-3-1
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    memcached:
        image: 'memcached:alpine'
        ports:
            - '11211:11211'
        networks:
            - network-swarm
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == docker-3-1
networks:
    network-swarm:
        external: true
